export const INITIAL_CLASSES = [
  "S1A (システム開発科 1年)",
  "S1B (システム開発科 1年)",
  "S2A (システム開発科 2年)",
  "W1A (Webクリエーター科 1年)",
  "W2A (Webクリエーター科 2年)",
  "G1A (ゲームクリエーター科 1年)",
  "G2A (ゲームクリエーター科 2年)",
  "G3A (ゲームクリエーター科 3年)",
  "K1A (情報処理科 1年)",
  "K2A (情報処理科 2年)",
  "教職員・実行委員会"
];

export const CATEGORIES = [
  "すべて",
  "調理器具・飲食",
  "ゲーム・アミューズメント",
  "文房具・事務用品",
  "装飾・会場設営"
];

export const INITIAL_EQUIPMENT = [
  { id: 1, name: "寸胴鍋(21cm)", category: "調理器具・飲食", stock: 2, unit: "個", description: "スープや調理用の小型寸胴鍋" },
  { id: 2, name: "寸胴鍋(36cm)", category: "調理器具・飲食", stock: 1, unit: "個", description: "模擬店での大量調理用中型寸胴鍋" },
  { id: 3, name: "寸胴鍋(39cm)", category: "調理器具・飲食", stock: 1, unit: "個", description: "大量仕込み用の大型寸胴鍋" },
  { id: 4, name: "ホットプレート", category: "調理器具・飲食", stock: 1, unit: "個", description: "鉄板焼き・焼きそば等用の電気ホットプレート" },
  { id: 5, name: "モール(紫)", category: "装飾・会場設営", stock: 2, unit: "個", description: "ブース装飾用のキラキラモール（紫）" },
  { id: 6, name: "モール(ピンク)", category: "装飾・会場設営", stock: 2, unit: "個", description: "ブース装飾用のキラキラモール（ピンク）" },
  { id: 7, name: "不織布マスク", category: "調理器具・飲食", stock: 2, unit: "箱", description: "衛生管理用の不織布マスク" },
  { id: 8, name: "ゴーグル", category: "装飾・会場設営", stock: 5, unit: "個", description: "演出・安全用の保護ゴーグル" },
  { id: 9, name: "フリスビー", category: "ゲーム・アミューズメント", stock: 6, unit: "個", description: "アトラクション用フリスビー" },
  { id: 10, name: "万華鏡", category: "ゲーム・アミューズメント", stock: 2, unit: "個", description: "体験展示用万華鏡" },
  { id: 11, name: "けんだま", category: "ゲーム・アミューズメント", stock: 2, unit: "個", description: "縁日・昔遊び用のけん玉" },
  { id: 12, name: "コマ、だるま落としセット", category: "ゲーム・アミューズメント", stock: 1, unit: "セット", description: "伝統的なおもちゃセット" },
  { id: 13, name: "ファミリールーレット", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "イベントゲーム用ルーレット" },
  { id: 14, name: "ビンゴカード", category: "ゲーム・アミューズメント", stock: 50, unit: "枚", description: "ビンゴ大会用カード" },
  { id: 15, name: "ルービックキューブ", category: "ゲーム・アミューズメント", stock: 2, unit: "個", description: "パズルアトラクション用" },
  { id: 16, name: "ハンドガン", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "的当てゲーム用トイガン" },
  { id: 17, name: "ぴこぴこハンマー", category: "ゲーム・アミューズメント", stock: 4, unit: "個", description: "音の出るプラスチックハンマー" },
  { id: 18, name: "カラーボール", category: "ゲーム・アミューズメント", stock: 5, unit: "個", description: "ボール投げゲーム用" },
  { id: 19, name: "へびのおもちゃ", category: "ゲーム・アミューズメント", stock: 5, unit: "個", description: "ジョークグッズ・装飾用" },
  { id: 20, name: "カエルのおもちゃ", category: "ゲーム・アミューズメント", stock: 3, unit: "個", description: "ジョークグッズ・装飾用" },
  { id: 21, name: "トカゲのおもちゃ", category: "ゲーム・アミューズメント", stock: 3, unit: "個", description: "ジョークグッズ・装飾用" },
  { id: 22, name: "的当て用的", category: "ゲーム・アミューズメント", stock: 9, unit: "個", description: "射的ブース用ターゲット" },
  { id: 23, name: "的当て用銃", category: "ゲーム・アミューズメント", stock: 7, unit: "個", description: "射的ブース用トイガン" },
  { id: 24, name: "bb弾セット", category: "ゲーム・アミューズメント", stock: 1, unit: "セット", description: "射的用BB弾" },
  { id: 25, name: "水ダンベル", category: "装飾・会場設営", stock: 1, unit: "個", description: "重し・演出用ダンベル" },
  { id: 26, name: "小さいボール", category: "ゲーム・アミューズメント", stock: 1, unit: "箱", description: "ボールすくい・ゲーム用" },
  { id: 27, name: "針ダーツボード", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "針タイプダーツ的" },
  { id: 28, name: "ダーツボード小", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "小型ダーツボード" },
  { id: 29, name: "簡易ダーツボード", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "マジックテープ式安全ダーツ" },
  { id: 30, name: "電子ダーツボード", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "自動スコア計測機能付きダーツ" },
  { id: 31, name: "本格的なダーツセット", category: "ゲーム・アミューズメント", stock: 1, unit: "セット", description: "バレル・フライト付き本格ダーツ" },
  { id: 32, name: "スリッパ", category: "装飾・会場設営", stock: 3, unit: "足", description: "室内履き・控室用" },
  { id: 33, name: "ダンボールナイフ", category: "文房具・事務用品", stock: 2, unit: "個", description: "荷ほどき・開梱用安全ナイフ" },
  { id: 34, name: "懐中電灯", category: "装飾・会場設営", stock: 5, unit: "個", description: "暗幕室・夜間作業用ライト" },
  { id: 35, name: "ミニホワイトボード", category: "文房具・事務用品", stock: 7, unit: "個", description: "メニュー案内・価格表示ボード" },
  { id: 36, name: "はぎれ(オレンジストライプ)", category: "装飾・会場設営", stock: 1, unit: "個", description: "クロス・装飾用布地" },
  { id: 37, name: "リボン(赤)", category: "装飾・会場設営", stock: 1, unit: "個", description: "ラッピング・装飾用赤リボン" },
  { id: 38, name: "カウンター", category: "文房具・事務用品", stock: 1, unit: "個", description: "来場者数カウント用手動数計" },
  { id: 39, name: "ビニールプール", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "ヨーヨー釣り・ボールすくい用" },
  { id: 40, name: "トランプ", category: "ゲーム・アミューズメント", stock: 3, unit: "個", description: "カードゲーム用トランプ" },
  { id: 41, name: "腕章(緑)", category: "装飾・会場設営", stock: 10, unit: "個", description: "スタッフ・係員用識別腕章（緑）" },
  { id: 42, name: "腕章(赤)", category: "装飾・会場設営", stock: 10, unit: "個", description: "実行委員・リーダー用腕章（赤）" },
  { id: 43, name: "サングラス", category: "装飾・会場設営", stock: 2, unit: "個", description: "衣装・ステージ演出用" },
  { id: 44, name: "カジノチップ(赤)", category: "ゲーム・アミューズメント", stock: 69, unit: "個", description: "ゲーム用トークンチップ（赤）" },
  { id: 45, name: "カジノチップ(青)", category: "ゲーム・アミューズメント", stock: 50, unit: "個", description: "ゲーム用トークンチップ（青）" },
  { id: 46, name: "カジノチップ(白)", category: "ゲーム・アミューズメント", stock: 20, unit: "個", description: "ゲーム用トークンチップ（白）" },
  { id: 47, name: "ストップウォッチ", category: "文房具・事務用品", stock: 5, unit: "個", description: "タイム計測用デジタルストップウォッチ" },
  { id: 48, name: "タイマー", category: "調理器具・飲食", stock: 3, unit: "個", description: "調理・制限時間計測用キッチンタイマー" },
  { id: 49, name: "布テープ", category: "文房具・事務用品", stock: 8, unit: "個", description: "掲示・会場設営用強力布テープ" },
  { id: 50, name: "荷ひも(ビニール)", category: "文房具・事務用品", stock: 1, unit: "個", description: "梱包・結束用ビニールひも" },
  { id: 51, name: "マッキー(8色)", category: "文房具・事務用品", stock: 7, unit: "個", description: "8色油性ペンセット" },
  { id: 52, name: "色えんぴつ(24色)", category: "文房具・事務用品", stock: 1, unit: "個", description: "24色入り色鉛筆セット" },
  { id: 53, name: "スティックのり", category: "文房具・事務用品", stock: 34, unit: "個", description: "POP作成用固形のり" },
  { id: 54, name: "水性マーカー(黒)", category: "文房具・事務用品", stock: 1, unit: "個", description: "筆記用黒色水性ペン" },
  { id: 55, name: "油性マーカー(黒)", category: "文房具・事務用品", stock: 10, unit: "個", description: "値札・看板用黒油性ペン" },
  { id: 56, name: "水性マーカー(赤)", category: "文房具・事務用品", stock: 1, unit: "個", description: "赤色水性ペン" },
  { id: 57, name: "油性マーカー(赤)", category: "文房具・事務用品", stock: 3, unit: "個", description: "強調・価格表示用赤油性ペン" },
  { id: 58, name: "水性マーカー(青)", category: "文房具・事務用品", stock: 6, unit: "個", description: "青色水性ペン" },
  { id: 59, name: "油性マーカー(青)", category: "文房具・事務用品", stock: 1, unit: "個", description: "青色油性ペン" },
  { id: 60, name: "水性マーカー(緑)", category: "文房具・事務用品", stock: 7, unit: "個", description: "緑色水性ペン" },
  { id: 61, name: "水性マーカー(紫)", category: "文房具・事務用品", stock: 3, unit: "個", description: "紫色水性ペン" },
  { id: 62, name: "水性マーカー(黄)", category: "文房具・事務用品", stock: 1, unit: "個", description: "黄色水性ペン" },
  { id: 63, name: "水性マーカー(茶)", category: "文房具・事務用品", stock: 0, unit: "個", description: "茶色水性ペン（現在在庫切）" },
  { id: 64, name: "水性マーカー(金)", category: "文房具・事務用品", stock: 1, unit: "個", description: "ゴールド水性マーカー" },
  { id: 65, name: "ビー玉", category: "ゲーム・アミューズメント", stock: 20, unit: "個", description: "ゲーム・すくい遊び用ビー玉" },
  { id: 66, name: "ビンゴ抽選機", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "ガラポン/手動式ビンゴマシン" },
  { id: 67, name: "ブーブークッション", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "ドッキリ・お笑い演出用" },
  { id: 68, name: "フードパック", category: "調理器具・飲食", stock: 8, unit: "パック", description: "食品提供用使い捨てテイクアウト容器" },
  { id: 69, name: "プラのスプーン", category: "調理器具・飲食", stock: 50, unit: "個", description: "試食用・提供用プラスチックスプーン" },
  { id: 70, name: "折り紙50色60枚", category: "文房具・事務用品", stock: 13, unit: "個", description: "装飾・子供コーナー用折り紙" },
  { id: 71, name: "ゴルフボール", category: "ゲーム・アミューズメント", stock: 15, unit: "個", description: "パターゴルフ・投球ゲーム用" },
  { id: 72, name: "ボールペン(黒)", category: "文房具・事務用品", stock: 8, unit: "個", description: "受付・記帳用黒ボールペン" },
  { id: 73, name: "ボールペン(青)", category: "文房具・事務用品", stock: 1, unit: "個", description: "青ボールペン" },
  { id: 74, name: "ボールペン(緑)", category: "文房具・事務用品", stock: 1, unit: "個", description: "緑ボールペン" },
  { id: 75, name: "カッター", category: "文房具・事務用品", stock: 1, unit: "個", description: "工作用カッターナイフ" },
  { id: 76, name: "はさみ", category: "文房具・事務用品", stock: 13, unit: "個", description: "紙切り・クラフト用ハサミ" },
  { id: 77, name: "定規", category: "文房具・事務用品", stock: 1, unit: "個", description: "直線定規" },
  { id: 78, name: "暗幕", category: "装飾・会場設営", stock: 9, unit: "枚", description: "お化け屋敷・映像展示用遮光カーテン" },
  { id: 79, name: "エプロン", category: "調理器具・飲食", stock: 8, unit: "個", description: "模擬店スタッフ用キッチンエプロン" },
  { id: 80, name: "台ふき", category: "調理器具・飲食", stock: 2, unit: "枚", description: "調理台・テーブル用クロス" },
  { id: 81, name: "三角巾", category: "調理器具・飲食", stock: 5, unit: "個", description: "調理従事者用バンダナ・三角巾" },
  { id: 82, name: "輪ゴム", category: "文房具・事務用品", stock: 2, unit: "箱", description: "袋留め・結束用輪ゴム" },
  { id: 83, name: "トング", category: "調理器具・飲食", stock: 3, unit: "個", description: "食品つかみ用ステンレススチールトング" },
  { id: 84, name: "装飾用ファー", category: "装飾・会場設営", stock: 4, unit: "個", description: "舞台・ブースデコレーション用ファー" },
  { id: 85, name: "アルミ針金", category: "装飾・会場設営", stock: 1, unit: "個", description: "看板固定・造形用針金" },
  { id: 86, name: "写真フレーム", category: "装飾・会場設営", stock: 9, unit: "個", description: "展示写真・POP表示用フレーム" },
  { id: 87, name: "計量カップ", category: "調理器具・飲食", stock: 1, unit: "個", description: "分量計測用500mlメジャーカップ" },
  { id: 88, name: "空気入れ", category: "装飾・会場設営", stock: 1, unit: "個", description: "風船・プール用エアポンプ" },
  { id: 89, name: "霧吹き", category: "調理器具・飲食", stock: 1, unit: "個", description: "清掃・調理補助用スプレーボトル" },
  { id: 90, name: "画用紙380×540", category: "文房具・事務用品", stock: 3, unit: "枚", description: "大型ポスター・看板用画用紙" },
  { id: 91, name: "画用紙A4", category: "文房具・事務用品", stock: 20, unit: "枚", description: "A4サイズ多目的画用紙" },
  { id: 92, name: "おもちゃの剣", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "演劇・撮影小道具用の剣" },
  { id: 93, name: "クリスマスモール", category: "装飾・会場設営", stock: 1, unit: "個", description: "装飾用モール" },
  { id: 94, name: "仮装用マスク", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "お化け屋敷・演出用仮面" },
  { id: 95, name: "竹トンボ", category: "ゲーム・アミューズメント", stock: 1, unit: "個", description: "伝統おもちゃ" },
  { id: 96, name: "お手玉", category: "ゲーム・アミューズメント", stock: 8, unit: "個", description: "ジャグリング・縁日用お手玉" },
  { id: 97, name: "両面テープ", category: "文房具・事務用品", stock: 1, unit: "個", description: "ポスター・POP貼り付け用強力両面テープ" },
  { id: 98, name: "養生テープ", category: "文房具・事務用品", stock: 2, unit: "個", description: "配線固定・跡が残らない養生テープ" },
  { id: 99, name: "トレー", category: "調理器具・飲食", stock: 3, unit: "個", description: "配膳・商品受け渡し用お盆" },
  { id: 100, name: "爪楊枝", category: "調理器具・飲食", stock: 1, unit: "箱", description: "試食用爪楊枝" },
  { id: 101, name: "割りばし", category: "調理器具・飲食", stock: 4, unit: "束", description: "飲食販売用割り箸" },
  { id: 102, name: "テーブルクロス", category: "装飾・会場設営", stock: 3, unit: "枚", description: "机の見た目を整えるカバークロス" },
  { id: 103, name: "ワイシャツ", category: "装飾・会場設営", stock: 3, unit: "着", description: "コスプレ・演劇用白シャツ" },
  { id: 104, name: "タコ糸", category: "文房具・事務用品", stock: 1, unit: "個", description: "看板吊り下げ・固定用強固な糸" },
  { id: 105, name: "ガス缶", category: "調理器具・飲食", stock: 9, unit: "本", description: "カセットコンロ用ブタンガス缶" },
  { id: 106, name: "グリーンシート小", category: "装飾・会場設営", stock: 6, unit: "枚", description: "床養生・展示スペース用シート" },
  { id: 107, name: "ブルーシート", category: "装飾・会場設営", stock: 3, unit: "枚", description: "大型防汚・荷物保護用ブルーシート" },
  { id: 108, name: "キッチンペーパー", category: "調理器具・飲食", stock: 1, unit: "パック", description: "油切り・拭き取り用ロールペーパー" },
  { id: 109, name: "木スプーン", category: "調理器具・飲食", stock: 60, unit: "個", description: "環境に優しい木製テイクアウトスプーン" },
  { id: 110, name: "やかん", category: "調理器具・飲食", stock: 2, unit: "個", description: "湯沸かし・ドリンク提供用ケトル" },
  { id: 111, name: "マドラー", category: "調理器具・飲食", stock: 4, unit: "本", description: "飲み物攪拌用マドラー" },
  { id: 112, name: "金属スプーン", category: "調理器具・飲食", stock: 4, unit: "本", description: "ステンレス製スプーン" },
  { id: 113, name: "レンジ対応プラスチックマグカップ", category: "調理器具・飲食", stock: 2, unit: "個", description: "電子レンジ加熱対応マグカップ" },
  { id: 114, name: "紙コップ", category: "調理器具・飲食", stock: 2, unit: "筒", description: "飲料提供用使い捨て紙コップ" },
  { id: 115, name: "デコレーションシール", category: "文房具・事務用品", stock: 2, unit: "個", description: "看板・POP飾付け用ステッカー" },
  { id: 116: "7色水性ペン", category: "文房具・事務用品", stock: 1, unit: "箱", description: "カラー水性ペン7色セット" },
  { id: 117: "写真たて", category: "装飾・会場設営", stock: 1, unit: "個", description: "卓上写真・案内用フォトスタンド" }
];
